### ISSUE TITLE
File not found

### ISSUE THREAD

**Issue by acad2** [hicksc/Basic-SPN-cryptanalysis#1] opened 2018-09-20 10:07 UTC
Got this error `FileNotFoundError: [Errno 2] No such file or directory: 'testData/9a284eb892b12cf803ca.dat'`

**Comment by hkscy** [comment] 2019-08-13 13:28
Hi, this was caused by the testData directory not being present in the project root. Have resolved in the latest commit. Thanks!

**Closed as completed by hkscy** 2019-08-13 13:28 UTC
